//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvTzRenameTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("avi,mpg,mkv,all")]
        public string Container {
            get {
                return ((string)(this["Container"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0TV,2HD,433,A4O,aAF,ANARCHY,ANiVCD,ARCHiViST,Argon,BaCKToRG,BAJSKORV,Ballerina,BamHD,BaraTV,BAWLS,BBV,BiA,BiQ,CHwDgB,C0NFUSED,COUNCiL,CREMOSA,CRiMSON,CTU,DGAS,DGX,DiCH,DiFFERENT,DIMENSION,DiSSENT,DOCUMENT,DOT,DRG,E7,ECHOS,ETACH,Football,FoV,FQM,FR34KTV,FTP,GNARLY,GORE,HDCP,HDi,HEH,Hype,IGUANA,iHT,iNBEV,iNCiTE,iNGOT,JMT,JUPiLER,KICKOFF,KYR,LionsDen,LMAO,LoKI,LOL,McCain,MiNT,MiRAGETV,MOMENTUM,MORiCH,MVM,NOsegmenT,NOTV,OCTi,OMiCRON,ORENJi,ORGANiC,OSiTV,PiX,POKERUS,PROXY,PusherCrew,PVR,RAP,REiSERADiO,REMAX,RiVER,RKcTV,RTA,SAiNTS,SFM,SiBV,SiSO,SiTV,SOF,SomeTV,SPAREL,STELLA,SVD,SYS,T33V33,TBS,TCM,TDF,TELEViSiON,TKO,TOKUS,T0nK4,TV/,TvD,TVFi,TVTUPA,TwoPhat,UTOPiA,VCDVaULT,W4F,WaLMaRT,WATERS,WPi,XOR,XOXO,XPRESS,YesTV,YT,0TV,2HD,433,A4O,aAF,ANARCHY,ANiVCD,ARCHiViST,Argon,BaCKToRG,BAJSKORV,Ballerina,BamHD,BaraTV,BAWLS,BBV,BiA,BiQ,CHwDgB,C0NFUSED,COUNCiL,CREMOSA,CRiMSON,CTU,DGAS,DGX,DiCH,DiFFERENT,DIMENSION,DiSSENT,DOCUMENT,DOT,DRG,E7,ECHOS,ETACH,Football,FoV,FQM,FR34KTV,FTP,GNARLY,GORE,HDCP,HDi,HEH,Hype,IGUANA,iHT,iNBEV,iNCiTE,iNGOT,JMT,JUPiLER,KICKOFF,KYR,LionsDen,LMAO,LoKI,LOL,McCain,MiNT,MiRAGETV,MOMENTUM,MORiCH,MVM,NOsegmenT,NOTV,OCTi,OMiCRON,ORENJi,ORGANiC,OSiTV,PiX,POKERUS,PROXY,PusherCrew,PVR,RAP,REiSERADiO,REMAX,RiVER,RKcTV,RTA,SAiNTS,SFM,SiBV,SiSO,SiTV,SOF,SomeTV,SPAREL,STELLA,SVD,SYS,T33V33,TBS,TCM,TDF,TELEViSiON,TKO,TOKUS,T0nK4,TV/,TvD,TVFi,TVTUPA,TwoPhat,UTOPiA,VCDVaULT,W4F,WaLMaRT,WATERS,WPi,XOR,XOXO,XPRESS,YesTV,YT,IMMERSE,ASAP,REWARD,FEVER,XII,BFF")]
        public string SceneName {
            get {
                return ((string)(this["SceneName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int _LogLevel {
            get {
                return ((int)(this["_LogLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CAMrip,CAM,TS,TELESYNC,PDVD,WP,WORKPRINT,SCR,SCREENER,DVDSCR,DVDSCREENER,BDSCR,DDC,R5,TC,TELECINE,DVDRip,DVDR,DVD-Rull,Full-Rip,TVRip,DSR,PDTV,HDTV,DVBRip,DTHRip,BDRip,BRRip,BDRip.XviD,1080p-BluRay-x264,720p-BluRay-x264,BDR,BluRay,BD5,BD9,720p,1080p,720i,1080i,PROPER,REPACK,WS,REAL")]
        public string SceneQuality {
            get {
                return ((string)(this["SceneQuality"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x264,H.261,DivX,XviD")]
        public string Codec {
            get {
                return ((string)(this["Codec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALF,CSI,NY,DEA,FLCL,JAG,CI,SVU,UK,USA,MAD,MASH,NCIS,QI,XL,II,NYC,UFC,UFO,WWE,PPV," +
            "RAW,HD,XIII")]
        public string ShowName {
            get {
                return ((string)(this["ShowName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.github.com/YaNightmare/TvTz-Rename-Tool/master/version.xml")]
        public string VersionXML {
            get {
                return ((string)(this["VersionXML"]));
            }
        }
    }
}
